services:
  monitor-svc:
    build: 
        context: services
        dockerfile: monitor-svc/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/data/
    links:
      - storage
    environment:
      - NGROK_TOKEN
      - LABELBOX_API_KEY
  inference-svc:
    build:
        context: services
        dockerfile: inference-svc/Dockerfile
    ports:
      - "5000:5000"
    links:
      - storage
      - inference-server
  inference-server:
    image: tensorflow/serving:latest
    environment:
      - MODEL_NAME=animaldet
    volumes:
      - /tmp/servable/saved_model:/models/animaldet 
  storage:
    build:
        context: services
        dockerfile: storage-svc/Dockerfile
    volumes:
      - ./storage:/home/sirius/data

