services:
  observe-svc:
    build: 
        context: .
        dockerfile: observe-svc/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/data/
    links:
      - storage
    environment:
      - NGROK_TOKEN
      - LABELBOX_API_KEY
  animal-svc:
    build:
        context: .
        dockerfile: animal-svc/Dockerfile
    ports:
      - "5000:5000"
    links:
      - storage
      - animal-server
  animal-server:
    image: tensorflow/serving:latest
    environment:
      - MODEL_NAME=animaldet
    volumes:
      - /tmp/servable/saved_model:/models/animaldet 
  storage:
    build:
        context: storage/
        dockerfile: Dockerfile
    volumes:
      - ./storage:/home/sirius/data

