{
 "title": "Model Monitoring",
 "time": { "from": "2021-04-09T02:36:08.482Z", "to": "2021-04-09T02:36:22.456Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Model Performance Dashboard\n\nModel performance monitoring using Labelbox         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Num Reviews",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "query": "SELECT count(\"external_id\") FROM \"model-stats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "external_id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ground Truth Labels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "query": "SELECT sum(\"labels\") FROM \"model-stats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "labels" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average Precision",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "select": [
      [
       { "params": [ "AP" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Recall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "query": "SELECT mean(\"AR1\") FROM \"model-stats\" WHERE $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "AR1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Confidence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "select": [
      [
       { "params": [ "mean_score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inference Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model-stats",
     "query": "SELECT \"AP\",  \"AR1\", \"review_score\", \"label_id\", \"external_id\", \"image_link\", \"datarow_link\" FROM \"model-stats\" WHERE (\"model_name\" = 'animal-detector') AND $timeFilter",
     "select": [
      [
       { "params": [ "AR10" ], "type": "field" }
      ],
      [
       { "params": [ "label_id" ], "type": "field" }
      ],
      [
       { "params": [ "AP50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model_name", "operator": "=", "value": "animal-detector" }
     ]
    }
   ]
  }
 ]
}