apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - env:
          image: storagecontainer
          name: storage
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /host/storage
              name: storage-volume
          ports:
            - containerPort: 9000
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0 # Shortcut to allowing write permissions. Don't use in production
      restartPolicy: Always
      volumes:
      - name: storage-volume
        hostPath:
          path: /host/storage
status: {}
